#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re

inpute = "103459,151908,Alton Sterlings son: Everyone needs to protest the right way, with peace,Guardian,Jessica Glenza,2016-07-13,2016.0,7.0,https://www.theguardian.com/us-news/2016/jul/13/alton-sterling-son-cameron-protesters-baton-rouge,The son of a Louisiana man whose father was shot and killed at   range by Baton Rouge police asked protesters for peace and no violence, none whatsoever. Cameron Sterling, the    son of Alton Sterling, whose death at the hands of police was caught on video, spoke about his father and protests.  Alton Sterling was killed by Baton Rouge police on 5 July at a convenience store, where he was said to be selling CDs. Baton Rouge police said in a statement that police were called to the convenience store because Sterling had allegedly threatened another patron with a gun.  The press conference on Wednesday is Cameron’s first since he broke into sobs at a nationally broadcast press conference with his mother, following his father’s death. I came to talk to everyone about one: the death of my father. And, two: about how I feel about people in general, said Cameron, whose distinctly young voice was calm and composed in front of the scrum of reporters at the Triple S convenience store. People, in general, no matter what the race, should come together as one united family. No more arguments, violence, crimes, said Cameron. Yes, you can protest, but I want everyone to protest the right way. Protest in peace  —   no guns, no drugs, no alcohol, no violence. Everyone needs to protest in the right way, with peace. No violence, none whatsoever.  Earlier on Wednesday, in an interview with CBS News, Cameron said he didn’t believe all police were bad and that all police shouldn’t be punished for other police’s crimes. The police in Dallas, Texas, they didn’t deserve that, said Cameron. Alton Sterling’s death spurred a Department of Justice investigation, protests across the country, and was one of the subjects of a march in Dallas on Thursday when a gunman attacked and killed five police officers there.  His was the first of two police shootings that week, including a shocking video of the shooting of” Minnesota man Philandro Castile, the aftermath of which was broadcast live on Facebook by his girlfriend"

a = re.split(r'\,\d{4}\-\d{2}\-\d{2}\,\d{4}\.\d\,\d+\.\d\,\"?(https://www\.\w+\.\w+(\/[\w\d\-\.]+)+)?\"?\,',inpute)
print(a[0])
